### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by mibe** [szczys/Larson-Scanner#1]
I plan to use and make some changes to this code in a project of mine, which will be Open Hardware. That naturally requires an suitable license, but I couldn't find any info on that.

So is this code available under an Open Source Software license?
I'd prefer the MIT license. :blush:

**Comment by szczys** [comment]
I prefer the MIT License as well. Sorry about not adding it by default, thank you for asking about this. I've added it with commit: 49989d5818e9184306e419328689258b0e34628b

**Comment by mibe** [comment]
Wow that response was fast. Thanks! :+1:

**Comment by szczys** [comment]
Never put off till tomorrow what you can do today.

-Mike Szczys
Managing Editor
Hackaday.com
@szczys
